version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: lnmp_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 517127
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - lnmp_network

  php:
    image: xiaoqiushui17/lnmp-php:latest
    container_name: lnmp_php
    restart: always
    volumes:
      - ./html:/var/www/html
    networks:
      - lnmp_network
    depends_on:
      - mysql

  nginx:
    image: xiaoqiushui17/lnmp-nginx:latest
    container_name: lnmp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - lnmp_network
    depends_on:
      - php

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - lnmp_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - lnmp_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - lnmp_network
  
networks:
  lnmp_network:
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
